/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as HomeRouteImport } from './routes/_home'
import { Route as HomeIndexRouteImport } from './routes/_home/index'
import { Route as HomeReportIndexRouteImport } from './routes/_home/report/index'
import { Route as HomeCertificateIndexRouteImport } from './routes/_home/certificate/index'

const HomeRoute = HomeRouteImport.update({
  id: '/_home',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeIndexRoute = HomeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HomeRoute,
} as any)
const HomeReportIndexRoute = HomeReportIndexRouteImport.update({
  id: '/report/',
  path: '/report/',
  getParentRoute: () => HomeRoute,
} as any)
const HomeCertificateIndexRoute = HomeCertificateIndexRouteImport.update({
  id: '/certificate/',
  path: '/certificate/',
  getParentRoute: () => HomeRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof HomeIndexRoute
  '/certificate': typeof HomeCertificateIndexRoute
  '/report': typeof HomeReportIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof HomeIndexRoute
  '/certificate': typeof HomeCertificateIndexRoute
  '/report': typeof HomeReportIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_home': typeof HomeRouteWithChildren
  '/_home/': typeof HomeIndexRoute
  '/_home/certificate/': typeof HomeCertificateIndexRoute
  '/_home/report/': typeof HomeReportIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/certificate' | '/report'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/certificate' | '/report'
  id:
    | '__root__'
    | '/_home'
    | '/_home/'
    | '/_home/certificate/'
    | '/_home/report/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  HomeRoute: typeof HomeRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_home': {
      id: '/_home'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_home/': {
      id: '/_home/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof HomeIndexRouteImport
      parentRoute: typeof HomeRoute
    }
    '/_home/report/': {
      id: '/_home/report/'
      path: '/report'
      fullPath: '/report'
      preLoaderRoute: typeof HomeReportIndexRouteImport
      parentRoute: typeof HomeRoute
    }
    '/_home/certificate/': {
      id: '/_home/certificate/'
      path: '/certificate'
      fullPath: '/certificate'
      preLoaderRoute: typeof HomeCertificateIndexRouteImport
      parentRoute: typeof HomeRoute
    }
  }
}

interface HomeRouteChildren {
  HomeIndexRoute: typeof HomeIndexRoute
  HomeCertificateIndexRoute: typeof HomeCertificateIndexRoute
  HomeReportIndexRoute: typeof HomeReportIndexRoute
}

const HomeRouteChildren: HomeRouteChildren = {
  HomeIndexRoute: HomeIndexRoute,
  HomeCertificateIndexRoute: HomeCertificateIndexRoute,
  HomeReportIndexRoute: HomeReportIndexRoute,
}

const HomeRouteWithChildren = HomeRoute._addFileChildren(HomeRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  HomeRoute: HomeRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
